[package]
name = "notan_math"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_pcg = "0.2.1"
glam = {version = "0.19", features = ["scalar-math"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = {version = "0.7.2"}

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = {version = "0.7.2", features = ["wasm-bindgen"]}
getrandom = { version = "0.2.3", features = ["js"] }