[package]
name = "notan_app"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.9"
notan_math = { path = "../notan_math" }
notan_macro = { path = "../notan_macro" }
notan_log = { path = "../notan_log" }
notan_graphics = { path = "../notan_graphics" }
notan_utils = { path = "../notan_utils" }
downcast-rs = "1.2"
indexmap = "1.6"
futures = "0.3"
platter = {version = "0.1.4", features = ["web-sys"] }
parking_lot =  { version = "0.11", features = ["wasm-bindgen"] }

[features]