[package]
name = "notan_winit"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan_app = { path = "../notan_app" }
winit = "0.23"
crossbeam-channel = "0.5"
