[package]
name = "notan_egui"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan_log = { path = "../notan_log" }
notan_app = { path = "../notan_app" }
notan_macro = { path = "../notan_macro" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui = "0.14.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui = { version = "0.14", default-features = false, features = ["single_threaded"] }