[package]
name = "notan_glyph"
version = "0.1.0"
authors = ["Nazarí González <nazari.nz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glyph_brush = "0.7.2"
notan_app = { path = "../notan_app" }
notan_log = { path = "../notan_log" }
notan_macro = { path = "../notan_macro" }
notan_math = { path = "../notan_math" }

[features]
default = ["basic_pipeline"]
basic_pipeline = []